-- MySQL Script generated by MySQL Workbench
-- Thu Nov  7 19:38:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`League`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`League` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `numberOfTeams` INT NOT NULL,
  `level` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stadium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stadium` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `capacity` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `League_id` INT NOT NULL,
  `Stadium_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `numberOfPlayers` INT NOT NULL,
  `position` INT NOT NULL,
  `coachName` VARCHAR(45) NOT NULL,
  `capitanName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Team_League_idx` (`League_id` ASC) VISIBLE,
  INDEX `fk_Team_Stadium1_idx` (`Stadium_id` ASC) VISIBLE,
  CONSTRAINT `fk_Team_League`
    FOREIGN KEY (`League_id`)
    REFERENCES `mydb`.`League` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_Stadium1`
    FOREIGN KEY (`Stadium_id`)
    REFERENCES `mydb`.`Stadium` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Team_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `date_of_birth` DATETIME NOT NULL,
  `number` INT NOT NULL,
  `salary` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Player_Team1_idx` (`Team_id` ASC) VISIBLE,
  CONSTRAINT `fk_Player_Team1`
    FOREIGN KEY (`Team_id`)
    REFERENCES `mydb`.`Team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coach` (
  `id` INT NOT NULL,
  `Team_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `date_of_birth` DATETIME NOT NULL,
  `salary` INT NOT NULL,
  `contractLength` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Coach_Team1_idx` (`Team_id` ASC) VISIBLE,
  CONSTRAINT `fk_Coach_Team1`
    FOREIGN KEY (`Team_id`)
    REFERENCES `mydb`.`Team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Owner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Team_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `date_of_birth` DATETIME NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Owner_Team1_idx` (`Team_id` ASC) VISIBLE,
  CONSTRAINT `fk_Owner_Team1`
    FOREIGN KEY (`Team_id`)
    REFERENCES `mydb`.`Team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Match` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Team_home_id` INT NOT NULL,
  `Team_away_id` INT NOT NULL,
  `League_id` INT NOT NULL,
  `homeGoals` INT NOT NULL,
  `awayGoals` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Match_Team1_idx` (`Team_home_id` ASC) VISIBLE,
  INDEX `fk_Match_Team2_idx` (`Team_away_id` ASC) VISIBLE,
  INDEX `fk_Match_League1_idx` (`League_id` ASC) VISIBLE,
  CONSTRAINT `fk_Match_Team1`
    FOREIGN KEY (`Team_home_id`)
    REFERENCES `mydb`.`Team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Team2`
    FOREIGN KEY (`Team_away_id`)
    REFERENCES `mydb`.`Team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_League1`
    FOREIGN KEY (`League_id`)
    REFERENCES `mydb`.`League` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PlayerStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PlayerStats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Player_id` INT NOT NULL,
  `apperances` INT NOT NULL,
  `minutesPlayed` INT NOT NULL,
  `goals` INT NOT NULL,
  `assists` INT NOT NULL,
  `contractLenght` DATETIME NOT NULL,
  `yellowCards` INT NOT NULL,
  `redCards` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_PlayerStats_Player1_idx` (`Player_id` ASC) VISIBLE,
  CONSTRAINT `fk_PlayerStats_Player1`
    FOREIGN KEY (`Player_id`)
    REFERENCES `mydb`.`Player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TeamStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TeamStats` (
  `id` INT NOT NULL,
  `Team_id` INT NOT NULL,
  `points` INT NOT NULL,
  `goalsScored` INT NOT NULL,
  `goalsAgainst` INT NOT NULL,
  `goalsDifference` INT NOT NULL,
  `cleanSheets` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TeamStats_Team1_idx` (`Team_id` ASC) VISIBLE,
  CONSTRAINT `fk_TeamStats_Team1`
    FOREIGN KEY (`Team_id`)
    REFERENCES `mydb`.`Team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MatchEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MatchEvent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Match_id` INT NOT NULL,
  `Player_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `minute` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_MatchEvent_Match1_idx` (`Match_id` ASC) VISIBLE,
  INDEX `fk_MatchEvent_Player1_idx` (`Player_id` ASC) VISIBLE,
  CONSTRAINT `fk_MatchEvent_Match1`
    FOREIGN KEY (`Match_id`)
    REFERENCES `mydb`.`Match` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MatchEvent_Player1`
    FOREIGN KEY (`Player_id`)
    REFERENCES `mydb`.`Player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
